export const contactStyles = {
    section: "py-16 bg-white",
    container: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8",
    wrapper: "grid grid-cols-1 lg:grid-cols-2 gap-12",
    heading: "text-center lg:text-left mb-10 lg:mb-0 lg:col-span-2",
    title: "text-3xl font-extrabold text-gray-900",
    formContainer: "order-2 lg:order-2",
    form: "grid grid-cols-1 gap-y-6",
    field: "block",
    label: "text-gray-700 font-medium mb-1 block",
    input: "w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 py-3 px-4 bg-gray-50 border",
    textarea: "w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 py-3 px-4 bg-gray-50 border h-32",
    button: "w-full inline-flex justify-center py-3 px-6 border border-transparent shadow-sm text-base font-medium rounded-md text-white bg-blue-900 hover:bg-blue-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-900 transition-colors duration-200",
    mapContainer: "order-1 lg:order-1 h-96 lg:h-auto bg-gray-200 rounded-lg shadow-lg overflow-hidden relative min-h-[400px]",
    mapPlaceholder: "absolute inset-0 flex items-center justify-center text-gray-500 font-medium",
};
